### ISSUE TITLE
Unknown option(s) 'password, userdn' in LDAP config.

### ISSUE THREAD

**Issue by iakovgan** [devpi/devpi-ldap#25]
looks like password and userdn are not in known_keys:  https://github.com/devpi/devpi-ldap/blob/master/devpi_ldap/main.py#L76

This makes impossible to use plugin with auth in ldap.

**Comment by mikenerone** [comment]
Those are the top-level keys. `password` and `userdn` are used _within_ the `user_search` and `group_search` dicts. Maybe I missed your point. :)

**Comment by iakovgan** [comment]
Thank you. My bad.
